name: Java CICD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install google-java-format
        run: |
          wget https://github.com/google/google-java-format/releases/download/v1.17.0/google-java-format-1.17.0-all-deps.jar -O google-java-format.jar

      - name: Run google-java-format
        run: |
          find . -name "*.java" | xargs java -jar google-java-format.jar --dry-run --set-exit-if-changed

      - name: Build with Maven
        run: mvn clean install
