name: Java CICD Kata
run-name: Java CICD Kata
on: [push]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download google-java-format
        run: |
          curl -L -o google-java-format.jar https://github.com/google/google-java-format/releases/download/v1.17.0/google-java-format-1.17.0-all-deps.jar

      - name: Format code (auto-fix)
        run: |
          find . -name "*.java" | xargs java -jar google-java-format.jar -i
      
